#!/usr/bin/env Rscript
# Read the instrument calls, verify them against the PHD exports, and draw the
# traces as editable TikZ paths. The script works with Rscript from the
# repository root and with Source in RStudio.
args <- commandArgs(FALSE)
script <- sub('^--file=', '', args[grepl('^--file=', args)])
if (length(script) == 1L) {
  root <- dirname(normalizePath(script))
} else if (basename(normalizePath(getwd())) == '06_hH3_sequence_validation') {
  root <- normalizePath(getwd())
} else {
  root <- normalizePath(file.path(getwd(), '06_hH3_sequence_validation'))
}
dataset_dir <- file.path(root, 'dataset')
output_dir <- file.path(root, 'output')
dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)
read_trace <- function(path) {
  bytes <- readBin(path, 'raw', n=file.info(path)$size)
  stopifnot(rawToChar(bytes[1:4])=='ABIF')
  uint <- function(off,size=4L) sum(as.integer(bytes[off+seq_len(size)]) * 256^((size-1):0))
  count<-uint(18); offset<-uint(26); tags<-list()
  for(i in seq_len(count)) {
    off<-offset+28*(i-1); name<-rawToChar(bytes[off+1:4]); number<-uint(off+4)
    size<-uint(off+16); address<-if(size<=4) off+20 else uint(off+20)
    tags[[paste0(name,'.',number)]]<-bytes[address+seq_len(size)]
  }
  shorts<-function(v) as.integer(v[seq(1,length(v),2)])*256L+as.integer(v[seq(2,length(v),2)])
  order<-strsplit(rawToChar(tags[['FWO_.1']]),'')[[1]]
  list(seq=rawToChar(tags[['PBAS.2']]),q=as.integer(tags[['PCON.2']]),
       pos=shorts(tags[['PLOC.2']]),traces=setNames(lapply(tags[paste0('DATA.',9:12)],shorts),order))
}
rc <- function(s) paste(rev(strsplit(chartr('ACGT','TGCA',s),'')[[1]]),collapse='')
files <- list.files(dataset_dir,pattern='\\.ab1$',full.names=TRUE)
records <- list(); checks <- list()
for (f in files) {
  d <- read_trace(f); key <- sub('_.*','',basename(f))
  oriented <- if(grepl('seq1',key)) d$seq else rc(d$seq)
  a <- regexpr('ATGGCCCGCACT',oriented,fixed=TRUE)[1]
  stopifnot(a>0,length(d$q)==nchar(d$seq),length(d$pos)==nchar(d$seq))
  codon <- substr(oriented,a+12,a+14)
  stopifnot(codon==if(startsWith(key,'28a')) 'AAG' else 'AGA')
  ii <- (a+12):(a+14)
  if(!grepl('seq1',key)) ii <- nchar(d$seq)+1-ii
  stopifnot(min(d$q[ii])>=50)
  phd <- list.files(dataset_dir,pattern=paste0('_',sub('\\.ab1$','',basename(f)),'.phd.1'),full.names=TRUE)
  stopifnot(length(phd)==1)
  lines <- readLines(phd); rows <- read.table(text=paste(lines[(match('BEGIN_DNA',lines)+1):(match('END_DNA',lines)-1)],collapse='\n'))
  stopifnot(paste(toupper(rows[[1]]),collapse='')==d$seq,
            identical(as.integer(rows[[2]]),d$q),identical(as.integer(rows[[3]]),d$pos))
  d$a <- a;records[[key]] <- d
  checks[[key]] <- data.frame(read=key,codon=codon,positions=paste(ii,collapse=','),Q=paste(d$q[ii],collapse=','),length=nchar(d$seq),phd_match=TRUE)
}
write.table(do.call(rbind,checks),file.path(output_dir,'verification.tsv'),sep='\t',quote=FALSE,row.names=FALSE)
con <- file(file.path(output_dir,'traces.tex'),'w')
emit <- function(...) writeLines(sprintf(...),con)
emit('%% Generated by script_hH3_sequence_validation.R using seqinr %s; no smoothing or base recalling.',packageVersion('seqinr'))
emit('\\begin{tikzpicture}[x=1cm,y=1cm]')
emit('\\useasboundingbox (0,0) rectangle (11.6,7.1);')
emit('\\filldraw[white] (0,0) rectangle (11.6,7.1);')
aa3 <- c(A='Ala',R='Arg',N='Asn',D='Asp',C='Cys',Q='Gln',E='Glu',G='Gly',H='His',I='Ile',L='Leu',K='Lys',M='Met',F='Phe',P='Pro',S='Ser',T='Thr',W='Trp',Y='Tyr',V='Val')
cols <- c(A='green!50!black',C='blue!80!black',G='black',T='red!80!black')
for (j in 1:2) {
 key <- c('28a-seq1','87a-seq1')[j]; d <- records[[key]];a<-d$a
 lo<-a-6;hi<-a+26;stopifnot(lo>0)
 left<-d$pos[lo]-7;right<-d$pos[hi]+7
 xx<-function(p) .12+11.3*(p-left)/(right-left)
 y<-c(3.75,.35)[j]
 label<-c('wild type (C1-T10-28a)','\\textit{hH3-K4R} (KNT-Op3-87a)')[j]
 emit('\\node[anchor=west,font=\\fontsize{10pt}{12pt}\\selectfont] at (0,%.3f) {%s};',y+2.75,label)
 emit('\\fill[yellow!20] (%.4f,%.4f) rectangle (%.4f,%.4f);',xx(d$pos[a+12])-.12,y,xx(d$pos[a+14])+.12,y+2.2)
 peak<-max(unlist(lapply(d$traces,function(t)t[(left:right)+1])))
 for (base in names(cols)) {
  t<-d$traces[[base]]; pts<-paste(sprintf('(%.4f,%.4f)',xx(left:right),y+1.55*t[(left:right)+1]/peak),collapse=' ')
  emit('\\draw[%s,line width=0.4pt] plot coordinates {%s};',cols[[base]],pts)
 }
 bases<-strsplit(d$seq,'')[[1]]
 for(i in lo:hi) emit('\\node[anchor=center,inner sep=0pt,font=\\ttfamily\\fontsize{8pt}{10pt}\\selectfont,text=%s] at (%.4f,%.4f) {%s};',cols[[bases[i]]],xx(d$pos[i]),y+1.72,bases[i])
 coding<-substr(d$seq,a,hi)
 aa<-seqinr::translate(strsplit(tolower(coding),'')[[1]])
 stopifnot(paste(toupper(aa[1:6]),collapse='')==if(j==1)'MARTKQ' else 'MARTRQ')
 for(k in seq_along(aa)) {
  ii<-(a+3*(k-1)):(a+3*(k-1)+2);cx<-xx(d$pos[ii[2]])
  emit('\\draw[gray!60,line width=0.3pt] (%.4f,%.4f) -- (%.4f,%.4f);',xx(d$pos[ii[1]]),y+1.91,xx(d$pos[ii[3]]),y+1.91)
  emit('\\node[anchor=center,inner sep=0pt,font=\\sffamily\\mdseries\\fontsize{9pt}{11pt}\\selectfont] at (%.4f,%.4f) {%s};',cx,y+2.09,aa3[[toupper(aa[k])]])
 }
}
emit('\\end{tikzpicture}');close(con)
writeLines(c(sub("[[:space:]]+$", "", capture.output(sessionInfo())),'Displayed: six bases upstream of ATG and nine translated codons.',
 'WT: MARTKQTAR; K4R: MARTRQTAR. Initiator M is shown; histone K4 is fifth translated codon.',
 'Signal DATA9-12 is scaled per read. PLOC values are zero-based; R indexes signal at PLOC+1.',
 'Four forward/reverse calls and their PHD exports match the previous Python verification.'),file.path(output_dir,'R-session.txt'))
message('Four AB1/PHD pairs verified; translated TikZ traces written.')
manifest <- list(R=R.version.string,seqinr=as.character(packageVersion('seqinr')),
 traces='R ABIF parser; DATA9-12/PBAS2/PLOC2; seqinr translation; native TikZ paths; independent scale; no smoothing or recalling',
 display=list(upstream_bases=6,translated_codons=9,aa_label_style='three-letter',translation_alignment='second nucleotide',trace_baselines_cm=c(3.75,.35),wild_type='MARTKQTAR',K4R='MARTRQTAR'),
 sources=setNames(lapply(list.files(dataset_dir,full.names=TRUE),function(p)digest::digest(file=p,algo='sha256')),
 list.files(dataset_dir)),checks=do.call(rbind,checks))
jsonlite::write_json(manifest,file.path(output_dir,'verification.json'),pretty=TRUE,auto_unbox=TRUE)
